language: go
go: tip

before_install:
 - go get github.com/BellerophonMobile/logberry
 
script:
 - go test -v .
 - go build examples/minimal/main.go
 - go generate examples/small/main.go
 - go build examples/small/main.go examples/small/build.go
